import Head from 'next/head'

const Home = () => {
  return (
    <div className="flex flex-col justify-center items-center py-0 px-2 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>sss</h1>
    </div>
  )
}

export default Home
